service: daily-scrum
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-2
  profile: gin1231
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
